"""Refresh data/processed/{dataset_description.json,DATASET_DESCRIPTION.md}
after a full embedding pass.

The smoke run of notebooks/data_prep.ipynb writes the original description
with `items_embedded` counts reflecting only the 2000-per-vertical cap. Once
data/embed_all.py finishes a full pass, every `has_text` item carries a real
MiniLM embedding. This script:
  - reads each vertical's item_features.npz and recounts items_embedded /
    items_placeholder from the actual text_emb rows
  - flips `embed_sample_size` in the snapshotted config to `0` (full run)
  - rewrites both the JSON and the Markdown
The non-embedding sections (select, clean, label distribution, splits,
pairs) are preserved unchanged — those numbers come from the pipeline and
didn't move.

Run from project root:
    .venv/bin/python data/regen_description.py
"""
from __future__ import annotations
import json, os, time
from pathlib import Path
import numpy as np

ROOT = Path("/Users/orimood/Desktop/homework/Amazon_CR")
PROCESSED = ROOT / "data" / "processed"
TRACKED_FIELDS = ['title', 'description', 'features', 'categories',
                  'main_category', 'store', 'details', 'price',
                  'average_rating', 'rating_number', 'images', 'author',
                  'bought_together']


def fmt(n):
    if isinstance(n, float):
        return f'{n:,.4f}' if abs(n) < 1 else f'{n:,.2f}'
    if isinstance(n, int):
        return f'{n:,d}'
    return str(n)


def atomic_write_text(target: Path, content: str) -> None:
    tmp = Path("/tmp") / f"_regen_{target.name}.{os.getpid()}.txt"
    tmp.write_text(content)
    os.replace(tmp, target)


def main():
    with open(PROCESSED / "dataset_description.json") as f:
        d = json.load(f)

    # ---- refresh embedding stats from the npzs ----
    for vert in d['config']['VERTICALS']:
        npz = PROCESSED / vert / "item_features.npz"
        z = np.load(npz, allow_pickle=True)
        emb = z['text_emb']
        nonzero = int((emb != 0).any(axis=1).sum())
        total   = int(emb.shape[0])
        d['verticals'][vert]['construct']['embedding'] = {
            'items_total':              total,
            'items_embedded':           nonzero,
            'items_placeholder':        total - nonzero,
            'cache_hits':               nonzero,  # post-hoc: all came from cache
            'texts_truncated_this_run': d['verticals'][vert]['construct']['embedding']
                                          .get('texts_truncated_this_run', 0),
        }

    d['snapshot_date'] = time.strftime('%Y-%m-%d')
    d['config']['embed_sample_size'] = 0  # we now have a full pass on disk
    d.setdefault('notes', []).append(
        f"Full embedding pass completed {d['snapshot_date']}: all has_text "
        "items carry real MiniLM vectors. Stats refreshed by /tmp/regen_description.py."
    )

    atomic_write_text(PROCESSED / "dataset_description.json",
                      json.dumps(d, indent=2, default=str))
    print(f"wrote dataset_description.json")

    # ---- rebuild DATASET_DESCRIPTION.md ----
    cfg = d['config']
    SNAPSHOT = d['snapshot_date']
    PAIR_SET = [tuple(p) for p in cfg['PAIRS']]
    lines = []
    P = lines.append

    P('# Dataset Description — CRISP-DM §3 Phase Output')
    P('')
    P(f'_Snapshot: {SNAPSHOT}._  '
      f'Generated by `notebooks/data_prep.ipynb`, refreshed by `data/regen_description.py` '
      f'after the full embedding pass.')
    P('')
    P(f'- **Verticals processed (Stage A):** {len(cfg["VERTICALS"])} — '
      f'{", ".join(cfg["VERTICALS"])}')
    P(f'- **Pairs bridged (Stage B):** {len(PAIR_SET)} '
      f'{"(includes reverse directions)" if cfg["ADD_REVERSE"] else ""}')
    P(f'- **Overlap floor:** {cfg["OVERLAP_FLOOR"]:,} shared users (sub-floor pairs flagged as R1)')
    P(f'- **Embedding model:** `{cfg["embed_model"]}` (dim={cfg["embed_dim"]}, '
      f'max_seq_length={cfg["max_seq_length"]}, L2-normalize={cfg["embed_normalize"]})')
    P(f'- **Embedding pass:** `embed_sample_size={cfg["embed_sample_size"]}` — full pass '
      f'(every `has_text` item carries a real MiniLM vector; the only placeholders are the'
      f' `has_text == False` items kept under the §3.2 fallback policy)')
    P(f'- **Split:** {cfg["split"]} {list(cfg["split_ratios"])}')
    P(f'- **Seed:** {cfg["seed"]}')
    P(f'- **Global category vocab size:** {fmt(d["category_vocab_size"])}')
    P('')

    P('## §3.1 / §3.2 — Per-vertical selection + cleaning')
    P('')
    P('| vertical | 0-core rows | dropped 0 | dropped 3 | 5-core rows | 5-core users | 5-core items | retention % | k |')
    P('|---|---:|---:|---:|---:|---:|---:|---:|---:|')
    for v in cfg['VERTICALS']:
        s = d['verticals'][v]['select']
        P(f'| `{v}` | {fmt(s["interactions_0core"])} | {fmt(s["dropped_rating_0"])} | '
          f'{fmt(s["dropped_rating_3"])} | {fmt(s["interactions_5core"])} | '
          f'{fmt(s["users_5core"])} | {fmt(s["items_5core"])} | '
          f'{s["retention_pct_vs_0core"]:.2f} | {s["k_core"]} |')
    P('')

    P('### Item-text fallback chain (§3.2)')
    P('')
    P('| vertical | items kept | primary | fallback | placeholder | orphans | dup pairs |')
    P('|---|---:|---:|---:|---:|---:|---:|')
    for v in cfg['VERTICALS']:
        c = d['verticals'][v]['clean']
        P(f'| `{v}` | {fmt(c["items_kept"])} | {fmt(c["text_primary"])} | '
          f'{fmt(c["text_fallback"])} | {fmt(c["text_none_placeholder"])} | '
          f'{fmt(c["orphan_interactions"])} | {fmt(c["duplicate_pairs"])} |')
    P('')

    P('### Per-field missing-value rates on kept items')
    P('')
    P('| field | ' + ' | '.join(f'`{v}`' for v in cfg['VERTICALS']) + ' |')
    P('|---|' + '|'.join(['---:'] * len(cfg['VERTICALS'])) + '|')
    for fld in TRACKED_FIELDS:
        row = [f'`{fld}`']
        for v in cfg['VERTICALS']:
            r = d['verticals'][v]['clean']['missing_value_rates'].get(fld, 0)
            row.append(f'{r*100:.2f}%')
        P('| ' + ' | '.join(row) + ' |')
    P('')

    P('## §3.3 — Construct: labels, embeddings, categories, popularity')
    P('')
    P('| vertical | positives | explicit_neg | dropped 3 | sampled_neg | items embedded | items placeholder | items total |')
    P('|---|---:|---:|---:|---:|---:|---:|---:|')
    for v in cfg['VERTICALS']:
        ld = d['verticals'][v]['construct']['label_distribution']
        em = d['verticals'][v]['construct']['embedding']
        P(f'| `{v}` | {fmt(ld["positives"])} | {fmt(ld["explicit_negatives"])} | '
          f'{fmt(ld["dropped_3"])} | {fmt(ld["sampled_negatives"])} | '
          f'{fmt(em["items_embedded"])} | {fmt(em["items_placeholder"])} | '
          f'{fmt(em["items_total"])} |')
    P('')

    P('## §3.5 — Format: per-vertical splits + ID vocabs')
    P('')
    P('| vertical | rows | users | items | train | val | test | train end | val end |')
    P('|---|---:|---:|---:|---:|---:|---:|---|---|')
    for v in cfg['VERTICALS']:
        f = d['verticals'][v]['format']
        sc = f['split_counts']
        co = f['cutoffs']
        P(f'| `{v}` | {fmt(f["rows"])} | {fmt(f["n_users"])} | {fmt(f["n_items"])} | '
          f'{fmt(sc.get("train", 0))} | {fmt(sc.get("val", 0))} | {fmt(sc.get("test", 0))} | '
          f'{co.get("train_end_date")} | {co.get("val_end_date")} |')
    P('')

    P('## §3.4 — Cross-vertical bridge (8 pairs)')
    P('')
    P('| pair | shared users | jaccard | source_only | target_only | active both sides | borderline |')
    P('|---|---:|---:|---:|---:|---:|:---:|')
    for src, tgt in PAIR_SET:
        s = d['pairs'][f'{src}__{tgt}']
        P(f'| `{src} -> {tgt}` | {fmt(s["shared_users"])} | {s["jaccard"]:.4f} | '
          f'{fmt(s["src_only_users"])} | {fmt(s["tgt_only_users"])} | '
          f'{fmt(s["shared_active_both_sides"])} | '
          f'{"YES" if s["borderline"] else "no"} |')
    P('')

    P('## Output schemas')
    P('')
    P('**Stage A — `data/processed/{vertical}/`**')
    P('')
    P('- `interactions.parquet` — `user_idx, item_idx, label, weight, rating, timestamp, split`')
    P('- `item_features.npz` — `text_emb (n,384), has_text (n,), text_source (n,), '
      'cat_indptr / cat_indices / cat_shape (sparse multi-hot), '
      'avg_rating (n,), rating_number_z (n,), item_idx_to_asin (n,)`')
    P('- `seen.parquet` — `user_idx, item_idx` (long form)')
    P('- `id_maps/user.parquet`, `id_maps/item.parquet`')
    P('')
    P('**Stage B — `data/processed/pairs/{SRC}__{TGT}/`**')
    P('')
    P('- `source_interactions.parquet`, `target_interactions.parquet` — same schema as Stage A,'
      ' but with the pair-global `user_idx`')
    P('- `shared_users.parquet` — `user_idx, src_pos_count, tgt_pos_count, '
      'src_first_ts, src_last_ts, tgt_first_ts, tgt_last_ts`')
    P('- `matched_pairs.parquet` — `user_idx, src_pos_count, tgt_pos_count` (the EMCDR training rows)')
    P('- `roles.parquet` — `user_idx, role ∈ {source_only, target_only, overlap}`')
    P('- `id_maps/user.parquet`, `meta.json`')

    atomic_write_text(PROCESSED / "DATASET_DESCRIPTION.md", '\n'.join(lines))
    print(f"wrote DATASET_DESCRIPTION.md")


if __name__ == "__main__":
    main()
